version: '3.0'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  redis:
    image: redis:6.0.10
    command: redis-server
    volumes:
      - 'redis_data:/data'
    ports:
      - 6380:6379
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
